export { ProductModule } from './productModule';
export { UserModule } from './userModule';
export { CouponModule } from './couponModule';
export { TaskModule } from './taskModule';
export { OrderModule } from './orderModule';
export { CheckInModule } from './checkInModule';
export { PrizeModule } from './prizeModule';
export { LuckyDrawModule } from './luckyDrawModule';
export { DisciplineModule } from './disciplineModule';
