export enum TASK_ACTION_ID {
  APPROVAL_REQUEST = 'APPROVAL_REQUEST',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  UPDATE_TASK = 'UPDATE_TASK',
  UPDATE_TASK_CATEGORY = 'UPDATE_TASK_CATEGORY',
  DELETE_TASK = 'DELETE_TASK',
  DELETE_TASK_CATEGORY = 'DELETE_TASK_CATEGORY',
}
