module.exports = {
    prefixer: false,
    compile: false,
    globalUtility: false,
    darkMode: 'media',
    corePlugins: {
        preflight: false,
        divideColor: false,
        divideOpacity: false,
        divideStyle: false,
        divideWidth: false,
        space: false,
        placeholderColor: false,
        placeholderOpacity: false,
    },
    theme: {
        spacing: {
            0: 0,
            1: '2px',
            2: '4px',
            4: '8px',
            8: '16px',
            12: '24px',
            16: '32px',
            20: '40px',
            24: '48px',
            32: '64px',
            40: '80px',
            48: '96px',
            56: '112px',
            64: '128px',
            72: '144px',
            80: '160px',
        },
        extend: {},
    },
};
