export enum COLOR_VARIABLES {
    COLOR_RED = '#FF69B4',
    COLOR_RED_1 = '#FFBBC6',
    COLOR_WHITE = '#FFF',
    COLOR_BLACK = '#000',
    TEXT_COLOR_BASE = '#333',
    TEXT_COLOR_DISABLED = '#CCC',
    COLOR_RATE_INACTIVE = '#CCC',
    COLOR_RATE_ACTIVE = '#FAB646',
    FILL_DISABLE = '#CCC',
    FILL_BODY = '#F4F4F4',
}

export enum PAGE_ID {
    LOGIN = 'login',
    HOME = 'home',
    SHOP_CART = 'shopCart',
    CHECKOUT = 'checkout',
    TASK = 'task',
    TASK_MANAGE = 'taskManage',
    TASK_CATEGORY_MANAGE = 'taskCategoryManage',
    TASK_FLOW_MANAGE = 'taskFlowManage',
    MINE = 'mine',
    COUPON = 'coupon',
    COUPON_MANAGE = 'couponManage',
    EXCHANGE_RECORD = 'exchangeRecord',
    CHECK_IN = 'checkIn',
    PRODUCT_MANAGE = 'productManage',
    PRODUCT_CATEGORY_MANAGE = 'productCategoryManage',
    PRODUCT_SEARCH = 'productSearch',
    PRODUCT_FRESH_ARRIVAL = 'productFreshArrival',
    LUCKY_DRAW = 'luckyDraw',
    LUCKY_DRAW_DETAIL = 'luckyDrawDetail',
    LUCKY_PRIZE_LIST = 'luckyPrizeList',
}