export enum PRODUCT_ACTION_ID {
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  UPDATE_PRODUCT_CATEGORY = 'UPDATE_PRODUCT_CATEGORY',
  DELETE_PRODUCT = 'DELETE_PRODUCT',
  DELETE_PRODUCT_CATEGORY = 'DELETE_PRODUCT_CATEGORY',
}
